baseURL = 'https://dovex4.github.io/'
languageCode = 'zh-cn'
title = '胶带的个人门户'
theme = "PaperMod"

[params.homeInfoParams]
    Title = "你好，我是胶带 👋"
    Content = "正在探索有意思的各种知识。"

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/DoveX4"
[[params.socialIcons]]
    name = "zhihu"
    url = "https://www.zhihu.com/people/aloneperson"
